---
name: ci

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      proto_ref:
      proto_sha:
  push:
    branches:
      - main
      - v*
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  # Run tests for PRs
  pull_request:

env:
  VAULT_ADDR: https://vault.eng.aserto.com/
  GO_VERSION: "1.23"
  GO_LANGCI_LINT_VERSION: "v1.61.0"
  GO_TESTSUM_VERSION: "1.11.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.CODEGEN_APP_ID }}
          private-key: ${{ secrets.CODEGEN_APP_KEY }}
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      -
        name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      -
        name: Install dependencies
        run: |
            go run mage.go deps
      -
        name: Clean generated code
        run: go run mage.go clean
      -
        name: Generate
        run: go run mage.go generate
      -
        name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: ${{ env.GO_LANGCI_LINT_VERSION }}
      -
        name: Test Setup
        uses: gertd/action-gotestsum@v3.0.0
        with:
          gotestsum_version: ${{ env.GO_TESTSUM_VERSION }}
      -
        name: Test
        run: |
          gotestsum --format short-verbose -- -count=1 -v -timeout=240s -coverprofile=cover.out -coverpkg=./... ./...
      -
        name: Upload code coverage
        uses: shogo82148/actions-goveralls@v1
        continue-on-error: true
        with:
          path-to-profile: cover.out
      -
        name: Commit changes
        id: commit_changes
        if: github.event_name == 'workflow_dispatch'
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Read Configuration
        uses: hashicorp/vault-action@v3
        id: vault
        with:
          url: ${{ env.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/readme  "README_OAS_DIRECTORY_KEY"     | README_OAS_DIRECTORY_KEY;
            kv/data/readme  "DIRECTORY_API_DEFINITION_ID"  | DIRECTORY_API_DEFINITION_ID;

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create openapi.readmeio.json
        run: |
            cat publish/directory/openapi.json  | jq ".servers=$(cat config/readmeio.servers.json)" > openapi.readmeio.json

      - name: Publish to readme.io
        uses: readmeio/rdme@v8
        with:
          rdme: >
            openapi ./openapi.readmeio.json
            --key=${{ steps.vault.outputs.README_OAS_DIRECTORY_KEY }}
            --id ${{ steps.vault.outputs.DIRECTORY_API_DEFINITION_ID }}

  dispatch-console-common-generate:
    needs: release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      -
        name: Read Configuration
        uses: hashicorp/vault-action@v3
        id: vault
        with:
          url: https://vault.eng.aserto.com/
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/github    "USERNAME"          | GH_USERNAME;
            kv/data/github    "READ_WRITE_TOKEN"  | GH_TOKEN;
      -
        name: Trigger dispatch
        run: |
          curl -XPOST -u "${GH_USERNAME}:${GH_TOKEN}" \
          -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" \
          https://api.github.com/repos/aserto-dev/console-common/actions/workflows/generate.yml/dispatches --data '{"ref": "main", "inputs": {"openapi_directory_version": "${{ github.ref_name }}" }}'
